name: Bug Report
description: A feature request form that should be reviewed by the developer
title: "[New Feature]: "
labels: ["enhancement"]
assignees:
  - johardi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form!
  - type: textarea
    id: new-feature-description
    attributes:
      label: Describe the new feature
      placeholder: Tell us what you see in 1-3 sentences!
    validations:
      required: true
